//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ImageWatch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ImageWatch.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address to Watch.
        /// </summary>
        public static string AddAddressToWatchMenuItem {
            get {
                return ResourceManager.GetString("AddAddressToWatchMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Watch.
        /// </summary>
        public static string AddToWatchMenuItem {
            get {
                return ResourceManager.GetString("AddToWatchMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAllMenuItem {
            get {
                return ResourceManager.GetString("CollapseAllMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Maximize Contrast.
        /// </summary>
        public static string ContextMenuAutoMaximizeText {
            get {
                return ResourceManager.GetString("ContextMenuAutoMaximizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Channel Pseudo Color.
        /// </summary>
        public static string ContextMenuColormapJetText {
            get {
                return ResourceManager.GetString("ContextMenuColormapJetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Channel Ignore Alpha.
        /// </summary>
        public static string ContextMenuFourChannelIgnoreAlphaText {
            get {
                return ResourceManager.GetString("ContextMenuFourChannelIgnoreAlphaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Pixel Address.
        /// </summary>
        public static string CopyPixelAddressMenuItem {
            get {
                return ResourceManager.GetString("CopyPixelAddressMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboardMenuItem {
            get {
                return ResourceManager.GetString("CopyToClipboardMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump to File.
        /// </summary>
        public static string DumpToFileMenuItem {
            get {
                return ResourceManager.GetString("DumpToFileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAllMenuItem {
            get {
                return ResourceManager.GetString("ExpandAllMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand New Items.
        /// </summary>
        public static string ExpandNewItemsMenuItem {
            get {
                return ResourceManager.GetString("ExpandNewItemsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal Display.
        /// </summary>
        public static string HexadecimalDisplayMenuItem {
            get {
                return ResourceManager.GetString("HexadecimalDisplayMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [invalid].
        /// </summary>
        public static string InvalidText {
            get {
                return ResourceManager.GetString("InvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        public static string InvalidTextWithoutBrackets {
            get {
                return ResourceManager.GetString("InvalidTextWithoutBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Thumbnails.
        /// </summary>
        public static string LargeThumbnailsMenuItem {
            get {
                return ResourceManager.GetString("LargeThumbnailsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Views.
        /// </summary>
        public static string LinkViewsMenuItem {
            get {
                return ResourceManager.GetString("LinkViewsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locals.
        /// </summary>
        public static string LocalsRadioButton {
            get {
                return ResourceManager.GetString("LocalsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [noinit].
        /// </summary>
        public static string NoInitText {
            get {
                return ResourceManager.GetString("NoInitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [no selection].
        /// </summary>
        public static string NoSelectionText {
            get {
                return ResourceManager.GetString("NoSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        public static string NotApplicableText {
            get {
                return ResourceManager.GetString("NotApplicableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        public static string NullText {
            get {
                return ResourceManager.GetString("NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [operator].
        /// </summary>
        public static string OperatorText {
            get {
                return ResourceManager.GetString("OperatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Watch.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string WatchRadioButton {
            get {
                return ResourceManager.GetString("WatchRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Fit.
        /// </summary>
        public static string ZoomToFitMenuItem {
            get {
                return ResourceManager.GetString("ZoomToFitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Original Size.
        /// </summary>
        public static string ZoomToOriginalSizeMenuItem {
            get {
                return ResourceManager.GetString("ZoomToOriginalSizeMenuItem", resourceCulture);
            }
        }
    }
}
